// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: biding/v1/biding.proto

package bidingv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BidingService_MakeBid_FullMethodName = "/biding.v1.BidingService/MakeBid"
)

// BidingServiceClient is the client API for BidingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BidingServiceClient interface {
	MakeBid(ctx context.Context, in *MakeBidRequest, opts ...grpc.CallOption) (*MakeBidResponse, error)
}

type bidingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBidingServiceClient(cc grpc.ClientConnInterface) BidingServiceClient {
	return &bidingServiceClient{cc}
}

func (c *bidingServiceClient) MakeBid(ctx context.Context, in *MakeBidRequest, opts ...grpc.CallOption) (*MakeBidResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MakeBidResponse)
	err := c.cc.Invoke(ctx, BidingService_MakeBid_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BidingServiceServer is the server API for BidingService service.
// All implementations must embed UnimplementedBidingServiceServer
// for forward compatibility.
type BidingServiceServer interface {
	MakeBid(context.Context, *MakeBidRequest) (*MakeBidResponse, error)
	mustEmbedUnimplementedBidingServiceServer()
}

// UnimplementedBidingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBidingServiceServer struct{}

func (UnimplementedBidingServiceServer) MakeBid(context.Context, *MakeBidRequest) (*MakeBidResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MakeBid not implemented")
}
func (UnimplementedBidingServiceServer) mustEmbedUnimplementedBidingServiceServer() {}
func (UnimplementedBidingServiceServer) testEmbeddedByValue()                       {}

// UnsafeBidingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BidingServiceServer will
// result in compilation errors.
type UnsafeBidingServiceServer interface {
	mustEmbedUnimplementedBidingServiceServer()
}

func RegisterBidingServiceServer(s grpc.ServiceRegistrar, srv BidingServiceServer) {
	// If the following call panics, it indicates UnimplementedBidingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BidingService_ServiceDesc, srv)
}

func _BidingService_MakeBid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MakeBidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BidingServiceServer).MakeBid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BidingService_MakeBid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BidingServiceServer).MakeBid(ctx, req.(*MakeBidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BidingService_ServiceDesc is the grpc.ServiceDesc for BidingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BidingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "biding.v1.BidingService",
	HandlerType: (*BidingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MakeBid",
			Handler:    _BidingService_MakeBid_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "biding/v1/biding.proto",
}
