// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: biding/v1/biding.proto

package bidingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Suit int32

const (
	Suit_SUIT_UNSPECIFIED Suit = 0
	Suit_SUIT_C           Suit = 1
	Suit_SUIT_D           Suit = 2
	Suit_SUIT_H           Suit = 3
	Suit_SUIT_S           Suit = 4
	Suit_SUIT_N           Suit = 5
)

// Enum value maps for Suit.
var (
	Suit_name = map[int32]string{
		0: "SUIT_UNSPECIFIED",
		1: "SUIT_C",
		2: "SUIT_D",
		3: "SUIT_H",
		4: "SUIT_S",
		5: "SUIT_N",
	}
	Suit_value = map[string]int32{
		"SUIT_UNSPECIFIED": 0,
		"SUIT_C":           1,
		"SUIT_D":           2,
		"SUIT_H":           3,
		"SUIT_S":           4,
		"SUIT_N":           5,
	}
)

func (x Suit) Enum() *Suit {
	p := new(Suit)
	*p = x
	return p
}

func (x Suit) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Suit) Descriptor() protoreflect.EnumDescriptor {
	return file_biding_v1_biding_proto_enumTypes[0].Descriptor()
}

func (Suit) Type() protoreflect.EnumType {
	return &file_biding_v1_biding_proto_enumTypes[0]
}

func (x Suit) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Suit.Descriptor instead.
func (Suit) EnumDescriptor() ([]byte, []int) {
	return file_biding_v1_biding_proto_rawDescGZIP(), []int{0}
}

type SpecialCall int32

const (
	SpecialCall_SPECIAL_CALL_UNSPECIFIED SpecialCall = 0
	SpecialCall_SPECIAL_CALL_PASS        SpecialCall = 1
	SpecialCall_SPECIAL_CALL_DOUBLE      SpecialCall = 2
	SpecialCall_SPECIAL_CALL_REDOUBLE    SpecialCall = 3
	SpecialCall_SPECIAL_CALL_BID         SpecialCall = 4
)

// Enum value maps for SpecialCall.
var (
	SpecialCall_name = map[int32]string{
		0: "SPECIAL_CALL_UNSPECIFIED",
		1: "SPECIAL_CALL_PASS",
		2: "SPECIAL_CALL_DOUBLE",
		3: "SPECIAL_CALL_REDOUBLE",
		4: "SPECIAL_CALL_BID",
	}
	SpecialCall_value = map[string]int32{
		"SPECIAL_CALL_UNSPECIFIED": 0,
		"SPECIAL_CALL_PASS":        1,
		"SPECIAL_CALL_DOUBLE":      2,
		"SPECIAL_CALL_REDOUBLE":    3,
		"SPECIAL_CALL_BID":         4,
	}
)

func (x SpecialCall) Enum() *SpecialCall {
	p := new(SpecialCall)
	*p = x
	return p
}

func (x SpecialCall) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SpecialCall) Descriptor() protoreflect.EnumDescriptor {
	return file_biding_v1_biding_proto_enumTypes[1].Descriptor()
}

func (SpecialCall) Type() protoreflect.EnumType {
	return &file_biding_v1_biding_proto_enumTypes[1]
}

func (x SpecialCall) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SpecialCall.Descriptor instead.
func (SpecialCall) EnumDescriptor() ([]byte, []int) {
	return file_biding_v1_biding_proto_rawDescGZIP(), []int{1}
}

type Seat int32

const (
	Seat_SEAT_UNSPECIFIED Seat = 0
	Seat_SEAT_N           Seat = 1
	Seat_SEAT_E           Seat = 2
	Seat_SEAT_S           Seat = 3
	Seat_SEAT_W           Seat = 4
)

// Enum value maps for Seat.
var (
	Seat_name = map[int32]string{
		0: "SEAT_UNSPECIFIED",
		1: "SEAT_N",
		2: "SEAT_E",
		3: "SEAT_S",
		4: "SEAT_W",
	}
	Seat_value = map[string]int32{
		"SEAT_UNSPECIFIED": 0,
		"SEAT_N":           1,
		"SEAT_E":           2,
		"SEAT_S":           3,
		"SEAT_W":           4,
	}
)

func (x Seat) Enum() *Seat {
	p := new(Seat)
	*p = x
	return p
}

func (x Seat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Seat) Descriptor() protoreflect.EnumDescriptor {
	return file_biding_v1_biding_proto_enumTypes[2].Descriptor()
}

func (Seat) Type() protoreflect.EnumType {
	return &file_biding_v1_biding_proto_enumTypes[2]
}

func (x Seat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Seat.Descriptor instead.
func (Seat) EnumDescriptor() ([]byte, []int) {
	return file_biding_v1_biding_proto_rawDescGZIP(), []int{2}
}

type Vulnerability int32

const (
	Vulnerability_VULNERABILITY_UNSPECIFIED Vulnerability = 0
	Vulnerability_VULNERABILITY_NONE        Vulnerability = 1
	Vulnerability_VULNERABILITY_NS_VUL      Vulnerability = 2
	Vulnerability_VULNERABILITY_EW_VUL      Vulnerability = 3
	Vulnerability_VULNERABILITY_BOTH_VUL    Vulnerability = 4
)

// Enum value maps for Vulnerability.
var (
	Vulnerability_name = map[int32]string{
		0: "VULNERABILITY_UNSPECIFIED",
		1: "VULNERABILITY_NONE",
		2: "VULNERABILITY_NS_VUL",
		3: "VULNERABILITY_EW_VUL",
		4: "VULNERABILITY_BOTH_VUL",
	}
	Vulnerability_value = map[string]int32{
		"VULNERABILITY_UNSPECIFIED": 0,
		"VULNERABILITY_NONE":        1,
		"VULNERABILITY_NS_VUL":      2,
		"VULNERABILITY_EW_VUL":      3,
		"VULNERABILITY_BOTH_VUL":    4,
	}
)

func (x Vulnerability) Enum() *Vulnerability {
	p := new(Vulnerability)
	*p = x
	return p
}

func (x Vulnerability) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Vulnerability) Descriptor() protoreflect.EnumDescriptor {
	return file_biding_v1_biding_proto_enumTypes[3].Descriptor()
}

func (Vulnerability) Type() protoreflect.EnumType {
	return &file_biding_v1_biding_proto_enumTypes[3]
}

func (x Vulnerability) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Vulnerability.Descriptor instead.
func (Vulnerability) EnumDescriptor() ([]byte, []int) {
	return file_biding_v1_biding_proto_rawDescGZIP(), []int{3}
}

type System int32

const (
	System_SYSTEM_UNSPECIFIED System = 0
	System_SYSTEM_SPUTNIK     System = 1
)

// Enum value maps for System.
var (
	System_name = map[int32]string{
		0: "SYSTEM_UNSPECIFIED",
		1: "SYSTEM_SPUTNIK",
	}
	System_value = map[string]int32{
		"SYSTEM_UNSPECIFIED": 0,
		"SYSTEM_SPUTNIK":     1,
	}
)

func (x System) Enum() *System {
	p := new(System)
	*p = x
	return p
}

func (x System) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (System) Descriptor() protoreflect.EnumDescriptor {
	return file_biding_v1_biding_proto_enumTypes[4].Descriptor()
}

func (System) Type() protoreflect.EnumType {
	return &file_biding_v1_biding_proto_enumTypes[4]
}

func (x System) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use System.Descriptor instead.
func (System) EnumDescriptor() ([]byte, []int) {
	return file_biding_v1_biding_proto_rawDescGZIP(), []int{4}
}

type Call struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          SpecialCall            `protobuf:"varint,1,opt,name=type,proto3,enum=biding.v1.SpecialCall" json:"type,omitempty"`
	Level         int32                  `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	Suit          Suit                   `protobuf:"varint,3,opt,name=suit,proto3,enum=biding.v1.Suit" json:"suit,omitempty"`
	Explanation   string                 `protobuf:"bytes,4,opt,name=explanation,proto3" json:"explanation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Call) Reset() {
	*x = Call{}
	mi := &file_biding_v1_biding_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Call) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Call) ProtoMessage() {}

func (x *Call) ProtoReflect() protoreflect.Message {
	mi := &file_biding_v1_biding_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Call.ProtoReflect.Descriptor instead.
func (*Call) Descriptor() ([]byte, []int) {
	return file_biding_v1_biding_proto_rawDescGZIP(), []int{0}
}

func (x *Call) GetType() SpecialCall {
	if x != nil {
		return x.Type
	}
	return SpecialCall_SPECIAL_CALL_UNSPECIFIED
}

func (x *Call) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *Call) GetSuit() Suit {
	if x != nil {
		return x.Suit
	}
	return Suit_SUIT_UNSPECIFIED
}

func (x *Call) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

type Hand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pbn           string                 `protobuf:"bytes,1,opt,name=pbn,proto3" json:"pbn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hand) Reset() {
	*x = Hand{}
	mi := &file_biding_v1_biding_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hand) ProtoMessage() {}

func (x *Hand) ProtoReflect() protoreflect.Message {
	mi := &file_biding_v1_biding_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hand.ProtoReflect.Descriptor instead.
func (*Hand) Descriptor() ([]byte, []int) {
	return file_biding_v1_biding_proto_rawDescGZIP(), []int{1}
}

func (x *Hand) GetPbn() string {
	if x != nil {
		return x.Pbn
	}
	return ""
}

type MakeBidRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PlayerHand     *Hand                  `protobuf:"bytes,1,opt,name=player_hand,json=playerHand,proto3" json:"player_hand,omitempty"`
	AuctionHistory []*Call                `protobuf:"bytes,2,rep,name=auction_history,json=auctionHistory,proto3" json:"auction_history,omitempty"`
	Vulnerability  Vulnerability          `protobuf:"varint,3,opt,name=vulnerability,proto3,enum=biding.v1.Vulnerability" json:"vulnerability,omitempty"`
	Dealer         Seat                   `protobuf:"varint,4,opt,name=dealer,proto3,enum=biding.v1.Seat" json:"dealer,omitempty"`
	SystemName     System                 `protobuf:"varint,5,opt,name=system_name,json=systemName,proto3,enum=biding.v1.System" json:"system_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MakeBidRequest) Reset() {
	*x = MakeBidRequest{}
	mi := &file_biding_v1_biding_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MakeBidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeBidRequest) ProtoMessage() {}

func (x *MakeBidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_biding_v1_biding_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeBidRequest.ProtoReflect.Descriptor instead.
func (*MakeBidRequest) Descriptor() ([]byte, []int) {
	return file_biding_v1_biding_proto_rawDescGZIP(), []int{2}
}

func (x *MakeBidRequest) GetPlayerHand() *Hand {
	if x != nil {
		return x.PlayerHand
	}
	return nil
}

func (x *MakeBidRequest) GetAuctionHistory() []*Call {
	if x != nil {
		return x.AuctionHistory
	}
	return nil
}

func (x *MakeBidRequest) GetVulnerability() Vulnerability {
	if x != nil {
		return x.Vulnerability
	}
	return Vulnerability_VULNERABILITY_UNSPECIFIED
}

func (x *MakeBidRequest) GetDealer() Seat {
	if x != nil {
		return x.Dealer
	}
	return Seat_SEAT_UNSPECIFIED
}

func (x *MakeBidRequest) GetSystemName() System {
	if x != nil {
		return x.SystemName
	}
	return System_SYSTEM_UNSPECIFIED
}

type MakeBidResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NextCall      *Call                  `protobuf:"bytes,1,opt,name=next_call,json=nextCall,proto3" json:"next_call,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MakeBidResponse) Reset() {
	*x = MakeBidResponse{}
	mi := &file_biding_v1_biding_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MakeBidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeBidResponse) ProtoMessage() {}

func (x *MakeBidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_biding_v1_biding_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeBidResponse.ProtoReflect.Descriptor instead.
func (*MakeBidResponse) Descriptor() ([]byte, []int) {
	return file_biding_v1_biding_proto_rawDescGZIP(), []int{3}
}

func (x *MakeBidResponse) GetNextCall() *Call {
	if x != nil {
		return x.NextCall
	}
	return nil
}

var File_biding_v1_biding_proto protoreflect.FileDescriptor

const file_biding_v1_biding_proto_rawDesc = "" +
	"\n" +
	"\x16biding/v1/biding.proto\x12\tbiding.v1\"\x8f\x01\n" +
	"\x04Call\x12*\n" +
	"\x04type\x18\x01 \x01(\x0e2\x16.biding.v1.SpecialCallR\x04type\x12\x14\n" +
	"\x05level\x18\x02 \x01(\x05R\x05level\x12#\n" +
	"\x04suit\x18\x03 \x01(\x0e2\x0f.biding.v1.SuitR\x04suit\x12 \n" +
	"\vexplanation\x18\x04 \x01(\tR\vexplanation\"\x18\n" +
	"\x04Hand\x12\x10\n" +
	"\x03pbn\x18\x01 \x01(\tR\x03pbn\"\x99\x02\n" +
	"\x0eMakeBidRequest\x120\n" +
	"\vplayer_hand\x18\x01 \x01(\v2\x0f.biding.v1.HandR\n" +
	"playerHand\x128\n" +
	"\x0fauction_history\x18\x02 \x03(\v2\x0f.biding.v1.CallR\x0eauctionHistory\x12>\n" +
	"\rvulnerability\x18\x03 \x01(\x0e2\x18.biding.v1.VulnerabilityR\rvulnerability\x12'\n" +
	"\x06dealer\x18\x04 \x01(\x0e2\x0f.biding.v1.SeatR\x06dealer\x122\n" +
	"\vsystem_name\x18\x05 \x01(\x0e2\x11.biding.v1.SystemR\n" +
	"systemName\"?\n" +
	"\x0fMakeBidResponse\x12,\n" +
	"\tnext_call\x18\x01 \x01(\v2\x0f.biding.v1.CallR\bnextCall*X\n" +
	"\x04Suit\x12\x14\n" +
	"\x10SUIT_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06SUIT_C\x10\x01\x12\n" +
	"\n" +
	"\x06SUIT_D\x10\x02\x12\n" +
	"\n" +
	"\x06SUIT_H\x10\x03\x12\n" +
	"\n" +
	"\x06SUIT_S\x10\x04\x12\n" +
	"\n" +
	"\x06SUIT_N\x10\x05*\x8c\x01\n" +
	"\vSpecialCall\x12\x1c\n" +
	"\x18SPECIAL_CALL_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11SPECIAL_CALL_PASS\x10\x01\x12\x17\n" +
	"\x13SPECIAL_CALL_DOUBLE\x10\x02\x12\x19\n" +
	"\x15SPECIAL_CALL_REDOUBLE\x10\x03\x12\x14\n" +
	"\x10SPECIAL_CALL_BID\x10\x04*L\n" +
	"\x04Seat\x12\x14\n" +
	"\x10SEAT_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06SEAT_N\x10\x01\x12\n" +
	"\n" +
	"\x06SEAT_E\x10\x02\x12\n" +
	"\n" +
	"\x06SEAT_S\x10\x03\x12\n" +
	"\n" +
	"\x06SEAT_W\x10\x04*\x96\x01\n" +
	"\rVulnerability\x12\x1d\n" +
	"\x19VULNERABILITY_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12VULNERABILITY_NONE\x10\x01\x12\x18\n" +
	"\x14VULNERABILITY_NS_VUL\x10\x02\x12\x18\n" +
	"\x14VULNERABILITY_EW_VUL\x10\x03\x12\x1a\n" +
	"\x16VULNERABILITY_BOTH_VUL\x10\x04*4\n" +
	"\x06System\x12\x16\n" +
	"\x12SYSTEM_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSYSTEM_SPUTNIK\x10\x012Q\n" +
	"\rBidingService\x12@\n" +
	"\aMakeBid\x12\x19.biding.v1.MakeBidRequest\x1a\x1a.biding.v1.MakeBidResponseB\x14Z\x12biding.v1;bidingv1b\x06proto3"

var (
	file_biding_v1_biding_proto_rawDescOnce sync.Once
	file_biding_v1_biding_proto_rawDescData []byte
)

func file_biding_v1_biding_proto_rawDescGZIP() []byte {
	file_biding_v1_biding_proto_rawDescOnce.Do(func() {
		file_biding_v1_biding_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_biding_v1_biding_proto_rawDesc), len(file_biding_v1_biding_proto_rawDesc)))
	})
	return file_biding_v1_biding_proto_rawDescData
}

var file_biding_v1_biding_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_biding_v1_biding_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_biding_v1_biding_proto_goTypes = []any{
	(Suit)(0),               // 0: biding.v1.Suit
	(SpecialCall)(0),        // 1: biding.v1.SpecialCall
	(Seat)(0),               // 2: biding.v1.Seat
	(Vulnerability)(0),      // 3: biding.v1.Vulnerability
	(System)(0),             // 4: biding.v1.System
	(*Call)(nil),            // 5: biding.v1.Call
	(*Hand)(nil),            // 6: biding.v1.Hand
	(*MakeBidRequest)(nil),  // 7: biding.v1.MakeBidRequest
	(*MakeBidResponse)(nil), // 8: biding.v1.MakeBidResponse
}
var file_biding_v1_biding_proto_depIdxs = []int32{
	1, // 0: biding.v1.Call.type:type_name -> biding.v1.SpecialCall
	0, // 1: biding.v1.Call.suit:type_name -> biding.v1.Suit
	6, // 2: biding.v1.MakeBidRequest.player_hand:type_name -> biding.v1.Hand
	5, // 3: biding.v1.MakeBidRequest.auction_history:type_name -> biding.v1.Call
	3, // 4: biding.v1.MakeBidRequest.vulnerability:type_name -> biding.v1.Vulnerability
	2, // 5: biding.v1.MakeBidRequest.dealer:type_name -> biding.v1.Seat
	4, // 6: biding.v1.MakeBidRequest.system_name:type_name -> biding.v1.System
	5, // 7: biding.v1.MakeBidResponse.next_call:type_name -> biding.v1.Call
	7, // 8: biding.v1.BidingService.MakeBid:input_type -> biding.v1.MakeBidRequest
	8, // 9: biding.v1.BidingService.MakeBid:output_type -> biding.v1.MakeBidResponse
	9, // [9:10] is the sub-list for method output_type
	8, // [8:9] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_biding_v1_biding_proto_init() }
func file_biding_v1_biding_proto_init() {
	if File_biding_v1_biding_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_biding_v1_biding_proto_rawDesc), len(file_biding_v1_biding_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_biding_v1_biding_proto_goTypes,
		DependencyIndexes: file_biding_v1_biding_proto_depIdxs,
		EnumInfos:         file_biding_v1_biding_proto_enumTypes,
		MessageInfos:      file_biding_v1_biding_proto_msgTypes,
	}.Build()
	File_biding_v1_biding_proto = out.File
	file_biding_v1_biding_proto_goTypes = nil
	file_biding_v1_biding_proto_depIdxs = nil
}
