// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: dds/v1/dds.proto

package ddsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDDTableRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pbn           string                 `protobuf:"bytes,1,opt,name=pbn,proto3" json:"pbn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDDTableRequest) Reset() {
	*x = GetDDTableRequest{}
	mi := &file_dds_v1_dds_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDDTableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDDTableRequest) ProtoMessage() {}

func (x *GetDDTableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dds_v1_dds_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDDTableRequest.ProtoReflect.Descriptor instead.
func (*GetDDTableRequest) Descriptor() ([]byte, []int) {
	return file_dds_v1_dds_proto_rawDescGZIP(), []int{0}
}

func (x *GetDDTableRequest) GetPbn() string {
	if x != nil {
		return x.Pbn
	}
	return ""
}

type PlayerResults struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	North         int32                  `protobuf:"varint,1,opt,name=north,proto3" json:"north,omitempty"`
	East          int32                  `protobuf:"varint,2,opt,name=east,proto3" json:"east,omitempty"`
	South         int32                  `protobuf:"varint,3,opt,name=south,proto3" json:"south,omitempty"`
	West          int32                  `protobuf:"varint,4,opt,name=west,proto3" json:"west,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerResults) Reset() {
	*x = PlayerResults{}
	mi := &file_dds_v1_dds_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerResults) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerResults) ProtoMessage() {}

func (x *PlayerResults) ProtoReflect() protoreflect.Message {
	mi := &file_dds_v1_dds_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerResults.ProtoReflect.Descriptor instead.
func (*PlayerResults) Descriptor() ([]byte, []int) {
	return file_dds_v1_dds_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerResults) GetNorth() int32 {
	if x != nil {
		return x.North
	}
	return 0
}

func (x *PlayerResults) GetEast() int32 {
	if x != nil {
		return x.East
	}
	return 0
}

func (x *PlayerResults) GetSouth() int32 {
	if x != nil {
		return x.South
	}
	return 0
}

func (x *PlayerResults) GetWest() int32 {
	if x != nil {
		return x.West
	}
	return 0
}

type GetDDTableResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Results       map[string]*PlayerResults `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDDTableResponse) Reset() {
	*x = GetDDTableResponse{}
	mi := &file_dds_v1_dds_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDDTableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDDTableResponse) ProtoMessage() {}

func (x *GetDDTableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dds_v1_dds_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDDTableResponse.ProtoReflect.Descriptor instead.
func (*GetDDTableResponse) Descriptor() ([]byte, []int) {
	return file_dds_v1_dds_proto_rawDescGZIP(), []int{2}
}

func (x *GetDDTableResponse) GetResults() map[string]*PlayerResults {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_dds_v1_dds_proto protoreflect.FileDescriptor

const file_dds_v1_dds_proto_rawDesc = "" +
	"\n" +
	"\x10dds/v1/dds.proto\x12\x06dds.v1\"%\n" +
	"\x11GetDDTableRequest\x12\x10\n" +
	"\x03pbn\x18\x01 \x01(\tR\x03pbn\"c\n" +
	"\rPlayerResults\x12\x14\n" +
	"\x05north\x18\x01 \x01(\x05R\x05north\x12\x12\n" +
	"\x04east\x18\x02 \x01(\x05R\x04east\x12\x14\n" +
	"\x05south\x18\x03 \x01(\x05R\x05south\x12\x12\n" +
	"\x04west\x18\x04 \x01(\x05R\x04west\"\xaa\x01\n" +
	"\x12GetDDTableResponse\x12A\n" +
	"\aresults\x18\x01 \x03(\v2'.dds.v1.GetDDTableResponse.ResultsEntryR\aresults\x1aQ\n" +
	"\fResultsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.dds.v1.PlayerResultsR\x05value:\x028\x012Q\n" +
	"\n" +
	"DDSService\x12C\n" +
	"\n" +
	"GegDDTable\x12\x19.dds.v1.GetDDTableRequest\x1a\x1a.dds.v1.GetDDTableResponseB\x0eZ\fdds.v1;ddsv1b\x06proto3"

var (
	file_dds_v1_dds_proto_rawDescOnce sync.Once
	file_dds_v1_dds_proto_rawDescData []byte
)

func file_dds_v1_dds_proto_rawDescGZIP() []byte {
	file_dds_v1_dds_proto_rawDescOnce.Do(func() {
		file_dds_v1_dds_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dds_v1_dds_proto_rawDesc), len(file_dds_v1_dds_proto_rawDesc)))
	})
	return file_dds_v1_dds_proto_rawDescData
}

var file_dds_v1_dds_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_dds_v1_dds_proto_goTypes = []any{
	(*GetDDTableRequest)(nil),  // 0: dds.v1.GetDDTableRequest
	(*PlayerResults)(nil),      // 1: dds.v1.PlayerResults
	(*GetDDTableResponse)(nil), // 2: dds.v1.GetDDTableResponse
	nil,                        // 3: dds.v1.GetDDTableResponse.ResultsEntry
}
var file_dds_v1_dds_proto_depIdxs = []int32{
	3, // 0: dds.v1.GetDDTableResponse.results:type_name -> dds.v1.GetDDTableResponse.ResultsEntry
	1, // 1: dds.v1.GetDDTableResponse.ResultsEntry.value:type_name -> dds.v1.PlayerResults
	0, // 2: dds.v1.DDSService.GegDDTable:input_type -> dds.v1.GetDDTableRequest
	2, // 3: dds.v1.DDSService.GegDDTable:output_type -> dds.v1.GetDDTableResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_dds_v1_dds_proto_init() }
func file_dds_v1_dds_proto_init() {
	if File_dds_v1_dds_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dds_v1_dds_proto_rawDesc), len(file_dds_v1_dds_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dds_v1_dds_proto_goTypes,
		DependencyIndexes: file_dds_v1_dds_proto_depIdxs,
		MessageInfos:      file_dds_v1_dds_proto_msgTypes,
	}.Build()
	File_dds_v1_dds_proto = out.File
	file_dds_v1_dds_proto_goTypes = nil
	file_dds_v1_dds_proto_depIdxs = nil
}
