// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: dds/v1/dds.proto

package ddsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DDSService_GegDDTable_FullMethodName = "/dds.v1.DDSService/GegDDTable"
)

// DDSServiceClient is the client API for DDSService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DDSServiceClient interface {
	GegDDTable(ctx context.Context, in *GetDDTableRequest, opts ...grpc.CallOption) (*GetDDTableResponse, error)
}

type dDSServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDDSServiceClient(cc grpc.ClientConnInterface) DDSServiceClient {
	return &dDSServiceClient{cc}
}

func (c *dDSServiceClient) GegDDTable(ctx context.Context, in *GetDDTableRequest, opts ...grpc.CallOption) (*GetDDTableResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDDTableResponse)
	err := c.cc.Invoke(ctx, DDSService_GegDDTable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DDSServiceServer is the server API for DDSService service.
// All implementations must embed UnimplementedDDSServiceServer
// for forward compatibility.
type DDSServiceServer interface {
	GegDDTable(context.Context, *GetDDTableRequest) (*GetDDTableResponse, error)
	mustEmbedUnimplementedDDSServiceServer()
}

// UnimplementedDDSServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDDSServiceServer struct{}

func (UnimplementedDDSServiceServer) GegDDTable(context.Context, *GetDDTableRequest) (*GetDDTableResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GegDDTable not implemented")
}
func (UnimplementedDDSServiceServer) mustEmbedUnimplementedDDSServiceServer() {}
func (UnimplementedDDSServiceServer) testEmbeddedByValue()                    {}

// UnsafeDDSServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DDSServiceServer will
// result in compilation errors.
type UnsafeDDSServiceServer interface {
	mustEmbedUnimplementedDDSServiceServer()
}

func RegisterDDSServiceServer(s grpc.ServiceRegistrar, srv DDSServiceServer) {
	// If the following call panics, it indicates UnimplementedDDSServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DDSService_ServiceDesc, srv)
}

func _DDSService_GegDDTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDDTableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DDSServiceServer).GegDDTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DDSService_GegDDTable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DDSServiceServer).GegDDTable(ctx, req.(*GetDDTableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DDSService_ServiceDesc is the grpc.ServiceDesc for DDSService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DDSService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dds.v1.DDSService",
	HandlerType: (*DDSServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GegDDTable",
			Handler:    _DDSService_GegDDTable_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dds/v1/dds.proto",
}
